### ISSUE TITLE
ENUM Change

### ISSUE THREAD

**Issue by PGP-Protector** [PitneyBowes/pitneybowes-shipping-api-csharp-openapi#4]
The ENUMs for 
Manifest.cs CarrierEnum and
Carrier.cs Carrier

Need to be updated for the current version of the API.
The current version of the API is using PBCS vs NEWGISTICS. 

Also the shippingapi.Test Nuget package RestSharp 105.1.0 is tagged with a high severity vulnerability

**Comment by am005si** [comment]
We have pushed in the fix in Git 
We are gong to push this to Nuget soon after further testing

**Comment by am005si** [comment]
issues fixed in new release https://www.nuget.org/packages/shippingapiv2/1.6.1
